{% set versions = {
    "2.06.11": "ceaced62d39e4e2a1469fa2f20662d4d370279b3209930250766db02f44ae8de"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "hepmc")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: "https://gitlab.cern.ch/hepmc/HepMC/-/archive/{{ version }}/HepMC-{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}
  folder: source

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make


test:
  source_files:
    - source/examples
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  commands:
    # Workaround for lack of CONDA_BUILD_SYSROOT variable in staged recipes
    - cd source/examples
    # example_UsingIterators
    - ${CXX} example_UsingIterators.cc -o example_UsingIterators -I${CONDA_PREFIX}/include -L${CONDA_PREFIX}/lib -lHepMC
    # example_EventSelection
    - ${CXX} example_EventSelection.cc -o example_EventSelection -I${CONDA_PREFIX}/include -L${CONDA_PREFIX}/lib -lHepMC
    # example_BuildEventFromScratch
    - ${CXX} example_BuildEventFromScratch.cc -o example_BuildEventFromScratch -I${CONDA_PREFIX}/include -L${CONDA_PREFIX}/lib -lHepMC

about:
  home: http://hepmc.web.cern.ch/hepmc/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: source/INSTALL
  summary: 'HepMC - a C++ Event Record for Monte Carlo Generators'

  description: |
           The HepMC package is an object oriented, C++ event record
           for High Energy Physics Monte Carlo generators and simulation.
           The original code was written by M. Dobbs and J.B. Hansen
            (Comput. Phys. Commun. 134 (2001) 41). Since the first
           implementation, the package has undergone several modifications
           and in particular, the latest HepMC3 series is a completely new
           re-write using currently available C++11 techniques.

extra:
  recipe-maintainers:
    - meiyasan
