{% set versions = {
    "3.3.0": "6f876091edcf7ee6d0c0db04e080056e89efc1a61abe62355d97ce8e735769d6",
    "2.06.11": "ceaced62d39e4e2a1469fa2f20662d4d370279b3209930250766db02f44ae8de"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

{% set version_major = int(version.split('.')[0]) %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "hepmc")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  {% if version_major < 3 %}
  url: https://gitlab.cern.ch/hepmc/HepMC/-/archive/{{ version }}/HepMC-{{ version }}.tar.gz
  {% else %}
  url: https://gitlab.cern.ch/hepmc/HepMC3/-/archive/{{ version }}/HepMC3-{{ version }}.tar.gz
  {% endif %}
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}
  folder: source
  patches:
    {% if version_major >= 3 %}
    # c.f. https://gitlab.cern.ch/hepmc/HepMC3/-/merge_requests/360
    - patches/readlink-macOS.patch  # [osx]
    - patches/pythia6.patch
    - patches/python3-fix.patch
    {% endif %}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cmake<4
    - make
  host:
    - python
    - zlib
    - bzip2
    - zstd
    - xz
    - pythia>=8.3
    - root

  run:
    - python
    - pythia>=8.3
    - root

test:
  source_files:
    - source/test
  requires:
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  commands:

    - HepMC3-config --prefix
    - HepMC3-config --cxxflags
    - HepMC3-config --ldflags
    - HepMC3-config --libdir

    - cd source/test
    - ${CXX} -std=c++11 testMass.cc -o testMass $(HepMC3-config --cxxflags --ldflags) -Wl,-rpath,"$(HepMC3-config --libdir)"
    - ./testMass

about:
  home: https://hepmc.web.cern.ch/hepmc/
  license: GPL-3.0-or-later
  license_file: source/COPYING
  summary: HepMC3 is a new rewrite of HepMC event record.
  description: |
    HepMC3 is a new rewrite of HepMC event record. It uses shared pointers
    for in-memory navigation and the POD concept for the persistency.
  dev_url: https://gitlab.cern.ch/hepmc/HepMC3

extra:
  recipe-maintainers:
    - meiyasan
